### ISSUE TITLE
Lantern not always able to find and start flashlight

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#1846]
This was on Windows 7:

  java.lang.RuntimeException: java.lang.Error: Flashlight executable not found in search path 
  	at org.lantern.proxy.pt.PluggableTransports.newTransport(PluggableTransports.java:40) 
  	at org.lantern.proxy.ProxyHolder.startPt(ProxyHolder.java:365) 
  	at org.lantern.proxy.ProxyHolder.startPtIfNecessary(ProxyHolder.java:351) 
  	at org.lantern.proxy.ProxyHolder.markConnected(ProxyHolder.java:171) 
  	at org.lantern.proxy.DefaultProxyTracker.successfullyConnectedToProxy(DefaultProxyTracker.java:414) 
  	at org.lantern.proxy.DefaultProxyTracker.doAddProxy(DefaultProxyTracker.java:342) 
  	at org.lantern.proxy.DefaultProxyTracker.addProxy(DefaultProxyTracker.java:240) 
  	at org.lantern.proxy.DefaultProxyTracker.addSingleFallbackProxy(DefaultProxyTracker.java:507) 
  	at org.lantern.proxy.DefaultProxyTracker.addFallbackProxies(DefaultProxyTracker.java:488) 
  	at org.lantern.proxy.DefaultProxyTracker.onNewS3Config(DefaultProxyTracker.java:161) 
  	at org.lantern.proxy.DefaultProxyTracker.init(DefaultProxyTracker.java:103) 
  	at org.lantern.Launcher.startNetworkServices(Launcher.java:412) 
  	at org.lantern.Launcher.onConnectivityChanged(Launcher.java:400) 
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
  	at java.lang.reflect.Method.invoke(Unknown Source) 
  	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74) 
  	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45) 
  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314) 
  	at com.google.common.eventbus.AsyncEventBus.access$001(AsyncEventBus.java:34) 
  	at com.google.common.eventbus.AsyncEventBus$1.run(AsyncEventBus.java:100) 
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
  	at java.lang.Thread.run(Unknown Source) 
  Caused by: java.lang.Error: Flashlight executable not found in search path 
  	at org.lantern.proxy.pt.BasePluggableTransport.initPtPath(BasePluggableTransport.java:263) 
  	at org.lantern.proxy.pt.BasePluggableTransport.<init>(BasePluggableTransport.java:66) 
  	at org.lantern.proxy.pt.Flashlight.<init>(Flashlight.java:57) 
  	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
  	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) 
  	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) 
  	at java.lang.reflect.Constructor.newInstance(Unknown Source) 
  	at org.lantern.proxy.pt.PluggableTransports.newTransport(PluggableTransports.java:29) 
  	... 24 more

**Comment by myleshorton** [comment]
Closing in favor of updated #2090
