### ISSUE TITLE
LittleProxy error closing connections

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#1978]
LogglyNotifications:
json:
nSimilarSuppressed: 0
reporterId: 8cbda74e00c50ddb77f026fc5dd958c5
fullMessage: An exception was thrown by org.littleshoot.proxy.impl.ConnectionFlow$3.operationComplete()
extra:
methodName: warn
language: zh
logLevel: WARN
country: CN
threadName: GetModeProxy-ProxyToServerWorker-5
osName: Mac OS X
osArch: x86_64
version: 1.5.10-21f3e4d
lineNumber: 151
timeZone: Asia/Shanghai
fallback: false
osVersion: 10.10.1
javaVersion: 1.6.0_65
locationInfo: io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151)
stackTrace:
java.util.NoSuchElementException: org.littleshoot.proxy.impl.ProxyToServerConnection
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:914)
at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:296)
at org.littleshoot.proxy.impl.ProxyToServerConnection.connectionFailed(ProxyToServerConnection.java:651)
at org.littleshoot.proxy.impl.ClientToProxyConnection.serverConnectionFailed(ClientToProxyConnection.java:480)
at org.littleshoot.proxy.impl.ConnectionFlow$3.operationComplete(ConnectionFlow.java:188)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:631)
at io.netty.util.concurrent.DefaultPromise.notifyListener(DefaultPromise.java:608)
at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:130)
at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
at org.littleshoot.proxy.impl.ConnectionFlow.fail(ConnectionFlow.java:182)
at org.littleshoot.proxy.impl.ConnectionFlow$2.operationComplete(ConnectionFlow.java:153)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:631)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:596)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:553)
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:417)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:184)
at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
at java.lang.Thread.run(Thread.java:695)
occurredAt: 1416275088575
key: io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151)
message: An exception was thrown by org.littleshoot.proxy.impl.ConnectionFlow$3.operationComplete()
Raw Message:

**Comment by myleshorton** [comment]
java
