### ISSUE TITLE
[controller] Presence available fails periodically with one of two errors

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2003]
```
org.lantern.ExceptionFilter doFilter: Uncaught exception: The referenced transaction has expired or is no longer valid.
java.lang.IllegalArgumentException: The referenced transaction has expired or is no longer valid.
    at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:45)
    at com.google.appengine.api.datastore.DatastoreApiHelper$AsyncCallWrapper.convertException(DatastoreApiHelper.java:74)
    at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:96)
    at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
    at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
    at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:71)
    at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:32)
    at com.google.appengine.api.datastore.TransactionImpl.rollback(TransactionImpl.java:164)
    at org.lantern.data.RetryingTransaction.run(RetryingTransaction.java:33)
    at org.lantern.data.Dao.processFallbackProxyHostAndPort(Dao.java:307)
```

or

```
Uncaught exception from servlet
com.google.appengine.api.xmpp.XMPPFailureException: Unknown error sending message
    at com.google.appengine.api.xmpp.XMPPServiceImpl.doMessageRpc(XMPPServiceImpl.java:343)
    at com.google.appengine.api.xmpp.XMPPServiceImpl.sendMessage(XMPPServiceImpl.java:242)
    at org.lantern.XmppAvailableServlet.sendResponse(XmppAvailableServlet.java:247)
    at org.lantern.XmppAvailableServlet.sendUpdateTime(XmppAvailableServlet.java:189)
    at org.lantern.XmppAvailableServlet.doPost(XmppAvailableServlet.java:120)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
```

Neither reports a root cause.

**Comment by jkb016** [comment]
I am also seeing this issue 
````
ava.lang.IllegalArgumentException: The referenced transaction has expired or is no longer valid.
	at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:54)
	at com.google.appengine.api.datastore.DatastoreApiHelper$1.convertException(DatastoreApiHelper.java:129)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:97)
	at com.google.appengine.api.datastore.Batcher$ReorderingMultiFuture.get(Batcher.java:131)
	at com.google.appengine.api.datastore.FutureHelper$TxnAwareFuture.get(FutureHelper.java:182)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.
````
