### ISSUE TITLE
[bug] Seeing "XMPP Connection closed on error" a fair amount

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2006]
```
 Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38aLantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN [Smack Packet Reader (0)] xmpp.XmppUtils.connectionClosedOnError (XmppUtils.java:566) - XMPP connection closed on error
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...0-1d38-403b-a3cd-c2f2c0e9af7e",\n "ut" : 300000\n}</body></message>... @365:19
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:325)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:43)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:70)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - INFO [Smack Packet Reader (0)] xmpp.XmppUtils.persistentXmppConnection (XmppUtils.java:289) - Removing stale connection
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - INFO [CometD-Sync-OnConnect-Thread] state.SyncService.run (SyncService.java:101) - Syncing with frontend...
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR [GetModeProxy-ClientToProxyWorker-6] impl.ClientToProxyConnection.exceptionCaught (ClientToProxyConnection.java:604) - (AWAITING_INITIAL) [id: 0x4b91d492, /127.0.0.1:64367 => /127.0.0.1:8787]: Caught an exception on ClientToProxyConnection
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR java.io.IOException: Զ������ǿ�ȹر���һ�����е����ӡ�
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at sun.nio.ch.SocketDispatcher.read0(Native Method)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at sun.nio.ch.SocketDispatcher.read(Unknown Source)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at sun.nio.ch.IOUtil.read(Unknown Source)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
Nov 24 04:01:48 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - ERROR at java.lang.Thread.run(Unknown Source) 
```

**Comment by atavism** [comment]
> That could totally be. The other question is why the reconnection logic isn't kicking in. That might be the easiest approach here. I'll take a peek at that as soon as I'm free.

Are the reconnections possibly failing as well, and we aren't seeing the errors about them? https://github.com/adamfisk/littleshoot-xmpp/blob/master/src/main/java/org/littleshoot/commom/xmpp/XmppUtils.java -- it looks like reconnection failures aren't being logged with the right log level so they wouldn't show up in Loggly, correct?
