### ISSUE TITLE
[lantern] Error connecting to and reading from statshub

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2007]
```
 Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN [StatsManager-Get-0] lantern.JsonUtils.decode (JsonUtils.java:84) - Error decoding JSON
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN java.net.SocketTimeoutException: Read timed out
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at java.net.SocketInputStream.socketRead0(Native Method)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at java.net.SocketInputStream.read(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at java.net.SocketInputStream.read(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at sun.security.ssl.InputRecord.readFully(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at sun.security.ssl.InputRecord.read(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at sun.security.ssl.AppInputStream.read(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at java.io.BufferedInputStream.fill(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at java.io.BufferedInputStream.read1(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at java.io.BufferedInputStream.read(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at sun.net.www.http.ChunkedInputStream.fastRead(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at sun.net.www.http.ChunkedInputStream.read(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at java.io.FilterInputStream.read(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.impl.Utf8StreamParser.loadMore(Utf8StreamParser.java:172)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.impl.Utf8StreamParser._parserNumber2(Utf8StreamParser.java:1064)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.impl.Utf8StreamParser.parseNumberText(Utf8StreamParser.java:1034)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:552)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:304)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:319)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:319)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1909)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.lantern.JsonUtils.decode(JsonUtils.java:82)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.lantern.monitoring.StatshubAPI.getStats(StatshubAPI.java:146)
Nov 24 02:35:50 107.170.123.187-1 logger: Lantern Client (5a4b47fdb8dd264567bb8a32adac38a0 / CN / Windows 8 / 1.5.9-05f5f31 / 1.7.0_25-b16) - WARN at org.lantern.monitoring.StatsManager$1.run(StatsManager.java:113) 
```

**Comment by oxtoacart** [comment]
We're not really using statshub anymore, clsoing.
