### ISSUE TITLE
[bug] panic on nil pointer in go-igdman

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2025]
Seeing this in production

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x500fd0]
goroutine 16 [running]:
runtime.panic(0x6b41e0, 0x98de22)
c:/go/src/pkg/runtime/panic.c:279 +0xe9
syscall.(*LazyDLL).Load(0x12696340, 0x0, 0x0)
c:/go/src/pkg/syscall/dll_windows.go:176
syscall.(*LazyProc).Find(0x12696360, 0x0, 0x0)
c:/go/src/pkg/syscall/dll_windows.go:238 +0xb3
syscall.(*LazyProc).mustFind(0x12696360)
c:/go/src/pkg/syscall/dll_windows.go:256 +0x2e
syscall.(*LazyProc).Addr(0x12696360, 0x69d820)
c:/go/src/pkg/syscall/dll_windows.go:265 +0x2e
syscall.GetStdHandle(0xfffffff6, 0x501210, 0x0, 0x0)
c:/go/src/pkg/syscall/zsyscall_windows_386.go:320 +0x40
syscall.getStdHandle(0xfffffff6, 0x70e708)
c:/go/src/pkg/syscall/syscall_windows.go:336 +0x2e
syscall.init()
c:/go/src/pkg/syscall/syscall_windows.go:330 +0xde
os.init()
c:/go/src/pkg/os/types_windows.go:104 +0x57
github.com/getlantern/golog.init()
/Users/ox/gobuild/src/github.com/getlantern/golog/golog.go:131 +0x47
github.com/getlantern/byteexec.init()
/Users/ox/gobuild/src/github.com/getlantern/byteexec/rename_windows.go:14 +0x52
github.com/getlantern/go-igdman/igdman.init()
/Users/ox/gobuild/src/github.com/getlantern/go-igdman/igdman/util_windows.go:35 +0x52
main.init()
/Users/ox/gobuild/src/github.com/getlantern/flashlight/terminate_when_orphaned_windows.go:27 +0x48
goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
c:/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
c:/go/src/pkg/runtime/proc.c:1445
goroutine 18 [runnable]:
bgsweep()
c:/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
c:/go/src/pkg/runtime/proc.c:1445
```

**Comment by uaalto** [comment]
Hunting for short-term and next release. Is this still happening?

**Comment by myleshorton** [comment]
Great question. I haven't seen it, but this is a great example of where that panic catcher would be super useful.

**Comment by uaalto** [comment]
I'll handle then https://github.com/getlantern/lantern/issues/2648 first, and if this is reproduced will come back for it.
