### ISSUE TITLE
[bug] Unable to getStats: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2038]
Seen in Loggly for version 1.5.13.  This might actually be the same as #2007?  That one was originally misreported as a JSON error, but found to be due to (possibly TLS-related) problems connecting.

```
    LogglyNotifications:

    json:
        nSimilarSuppressed: 0
        reporterId: 33b704a4f8c11dfdff0203706d375aa6
        fullMessage: Unable to getStats: Remote host closed connection during handshake
        extra:
            methodName: run
            language: en
            logLevel: WARN
            country: US
            threadName: StatsManager-Get-0
            osName: Windows 7
            osArch: x86
            version: 1.5.13-3058b46
            lineNumber: 129
            timeZone: Asia/Tehran
            fallback: false
            osVersion: 6.1
            javaVersion: 1.8.0
        locationInfo: org.lantern.monitoring.StatsManager$1.run(StatsManager.java:129)
        stackTrace:
        javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at org.lantern.monitoring.StatshubAPI.getStats(StatshubAPI.java:138)
        at org.lantern.monitoring.StatsManager$1.run(StatsManager.java:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(Unknown Source)
        ... 18 more
        occurredAt: 1417788231026
        key: org.lantern.monitoring.StatsManager$1.run(StatsManager.java:129)
        message: Unable to getStats: Remote host closed connection during handshake
    http:
        clientHost: 128.199.178.33
        contentType: application/x-www-form-urlencoded
```

**Comment by uaalto** [comment]
This belongs to Lantern 1.x, i.e. Java version? Should we close it?

**Comment by myleshorton** [comment]
Yes thanks @uaalto!
