### ISSUE TITLE
[bug] [lantern] IO exception while trying to refresh token

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2074]
Likely a recurrence of #1850, though the root cause may be different.

Likely related to other proxying issues like #2006.

```
java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(Unknown Source)
at java.net.SocketInputStream.read(Unknown Source)
at sun.security.ssl.InputRecord.readFully(Unknown Source)
at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
at sun.security.ssl.InputRecord.read(Unknown Source)
at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:494)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.updateSecureConnection(DefaultClientConnectionOperator.java:232)
at org.apache.http.impl.conn.ManagedClientConnectionImpl.layerProtocol(ManagedClientConnectionImpl.java:401)
at org.apache.http.impl.client.DefaultRequestDirector.establishRoute(DefaultRequestDirector.java:840)
at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:647)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
at com.google.api.client.http.apache.ApacheHttpRequest.execute(ApacheHttpRequest.java:67)
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:980)
at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:299)
at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:323)
at org.lantern.oauth.OauthUtils.oauthTokens(OauthUtils.java:171)
at org.lantern.oauth.OauthUtils.accessToken(OauthUtils.java:281)
at org.lantern.oauth.OauthUtils.configureOauth(OauthUtils.java:272)
at org.lantern.oauth.OauthUtils.httpRequest(OauthUtils.java:238)
at org.lantern.oauth.OauthUtils.access$400(OauthUtils.java:52)
at org.lantern.oauth.OauthUtils$2.call(OauthUtils.java:229)
at org.lantern.oauth.OauthUtils$2.call(OauthUtils.java:224)
at org.lantern.oauth.OauthUtils$HttpFallbackFunc.execute(OauthUtils.java:143)
at org.lantern.oauth.OauthUtils.httpRequest(OauthUtils.java:232)
at org.lantern.oauth.OauthUtils.getRequest(OauthUtils.java:214)
at org.lantern.S3ConfigFetcher.fetchRemoteConfig(S3ConfigFetcher.java:152)
at org.lantern.S3ConfigFetcher.downloadAndCompareConfig(S3ConfigFetcher.java:124)
at org.lantern.S3ConfigFetcher.recheck(S3ConfigFetcher.java:104)
at org.lantern.S3ConfigFetcher.access$000(S3ConfigFetcher.java:25)
at org.lantern.S3ConfigFetcher$1.run(S3ConfigFetcher.java:97)
at java.util.TimerThread.mainLoop(Unknown Source)
at java.util.TimerThread.run(Unknown Source)
```

**Comment by myleshorton** [comment]
The manifestation of this will be an inability to view and add friends, login to XMPP, and anything Google. If this happens during the setup sequence, it's unclear what exactly would happen. The friends screen would probably hang, but you should be able to move on.

This would also mean that you don't get a fallback proxy and are in flashlight land, but with domain fronting working and if the user can still move on in the UI, the pain is relatively low.
