### ISSUE TITLE
Exception deleting port mapping

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#2091]
This will typically happen if there's no IGD, for example:

```
LogglyNotifications:
json:
nSimilarSuppressed: 0
reporterId: 894b70d0b5be852b6f93da24f81c6f8b
fullMessage: Exception deleting port mapping
extra:
methodName: run
language: zh
logLevel: ERROR
country: CN
threadName: UPnP-Mapping-Thread
osName: Windows 8
osArch: x86
version: 1.5.15-0dfae82
lineNumber: 132
timeZone: Asia/Shanghai
fallback: false
osVersion: 6.2
javaVersion: 1.7.0_25
locationInfo: org.lantern.UpnpCli$3.run(UpnpCli.java:132)
stackTrace:
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:402)
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:164)
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:151)
at org.lantern.UpnpCli.runCommand(UpnpCli.java:162)
at org.lantern.UpnpCli.access$200(UpnpCli.java:29)
at org.lantern.UpnpCli$3.run(UpnpCli.java:130)
at java.lang.Thread.run(Unknown Source)
occurredAt: 1418826494004
key: org.lantern.UpnpCli$3.run(UpnpCli.java:132)
message: Exception deleting port mapping
http:
clientHost: 162.243.197.249
contentType: application/x-www-form-urlencoded
```

**Comment by aranhoide** [comment]
This still happens in 1.5.15, although the fix is older than 2 weeks.  Please close again if this is expected (i.e. if the fix is scheduled for next version instead).

```
json:
nSimilarSuppressed: 0
reporterId: fb544123dee415961020c48fa5582141
fullMessage: Exception deleting port mapping
extra:
methodName: run
language: en
logLevel: ERROR
country: US
threadName: UPnP-Mapping-Thread
osName: Windows 7
shuttingDown: false
osArch: x86
version: 1.5.15-83ff811
lineNumber: 132
timeZone: Asia/Shanghai
fallback: false
osVersion: 6.1
javaVersion: 1.7.0_71
locationInfo: org.lantern.UpnpCli$3.run(UpnpCli.java:132)
stackTrace:
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:402)
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:164)
at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:151)
at org.lantern.UpnpCli.runCommand(UpnpCli.java:162)
at org.lantern.UpnpCli.access$200(UpnpCli.java:29)
at org.lantern.UpnpCli$3.run(UpnpCli.java:130)
at java.lang.Thread.run(Unknown Source)
occurredAt: 1420209631508
key: org.lantern.UpnpCli$3.run(UpnpCli.java:132)
message: Exception deleting port mapping
http:
clientHost: 112.198.83.145
contentType: application/x-www-form-urlencoded
Raw Message:
```

**Comment by myleshorton** [comment]
Yeah this was fixed on devel.
