### ISSUE TITLE
[bug] New problems extracting flashlight

### ISSUE THREAD

**Issue by oxtoacart** [getlantern/lantern#2168]
Observed on branch issue-2164 while running in Give mode:

```
11762  2015-01-13 08:18:41,210 INFO  [Lantern-Async-Event-Thread-0] lantern.LanternUtils.extractExecutableFromJar (LanternUtils.java:1285) - File /Users/ox.to.a.cart/.lantern/flashlight is out of date, deleting
11764  2015-01-13 08:18:41,212 INFO  [Lantern-Async-Event-Thread-1] lantern.LanternUtils.extractExecutableFromJar (LanternUtils.java:1285) - File /Users/ox.to.a.cart/.lantern/flashlight is out of date, deleting
11845  2015-01-13 08:18:41,293 INFO  [Lantern-Async-Event-Thread-0] lantern.LanternUtils.extractExecutableFromJar (LanternUtils.java:1292) - Moving /var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/1421158720098-0/flashlight to /Users/ox.to.a.cart/.lantern/flashlight
11846  2015-01-13 08:18:41,294 INFO  [Lantern-Async-Event-Thread-0] pt.BasePluggableTransport.startClient (BasePluggableTransport.java:125) - Starting Flashlight client
11848  2015-01-13 08:18:41,296 WARN  [Lantern-Async-Event-Thread-1] lantern.LanternUtils.extractExecutableFromJar (LanternUtils.java:1288) - Could not delete old file at /Users/ox.to.a.cart/.lantern/flashlight
11849  2015-01-13 08:18:41,297 INFO  [Lantern-Async-Event-Thread-1] lantern.LanternUtils.extractExecutableFromJar (LanternUtils.java:1292) - Moving /var/folders/j_/9dywssj524gf3100s4q9l48w0000gp/T/1421158719775-0/flashlight to /Users/ox.to.a.cart/.lantern/flashlight
11850  2015-01-13 08:18:41,298 ERROR [Lantern-Async-Event-Thread-1] lantern.LanternUtils.extractExecutableFromJar (LanternUtils.java:1299) - Unable to move file to destination /Users/ox.to.a.cart/.lantern/flashlight: Destination '/Users/ox.to.a.cart/.lantern/flashlight' already exists
11860  2015-01-13 08:18:41,308 ERROR [Lantern-Async-Event-Thread-1] impl.DefaultHttpProxyServer.uncaughtException (DefaultHttpProxyServer.java:440) - Uncaught throwable
java.lang.Error: Could not extract jar file from 'pt/flashlight/flashlight': Unable to move file to destination /Users/ox.to.a.cart/.lantern/flashlight: Destination '/Users/ox.to.a.cart/.lantern/flashlight' already exists
	at org.lantern.proxy.pt.BasePluggableTransport.<init>(BasePluggableTransport.java:71)
	at org.lantern.proxy.pt.Flashlight.<init>(Flashlight.java:57)
	at org.lantern.proxy.pt.FlashlightServerManager.runFlashlight(FlashlightServerManager.java:161)
	at org.lantern.proxy.pt.FlashlightServerManager.startFlashlight(FlashlightServerManager.java:119)
	at org.lantern.proxy.pt.FlashlightServerManager.update(FlashlightServerManager.java:103)
	at org.lantern.proxy.pt.FlashlightServerManager.onConnectivityChanged(FlashlightServerManager.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.AsyncEventBus.access$001(AsyncEventBus.java:34)
	at com.google.common.eventbus.AsyncEventBus$1.run(AsyncEventBus.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unable to move file to destination /Users/ox.to.a.cart/.lantern/flashlight: Destination '/Users/ox.to.a.cart/.lantern/flashlight' already exists
	at org.lantern.LanternUtils.extractExecutableFromJar(LanternUtils.java:1300)
	at org.lantern.proxy.pt.BasePluggableTransport.<init>(BasePluggableTransport.java:68)
	... 17 more
```

**Comment by oxtoacart** [comment]
This was a race condition between checking for the existence of the PT file and extracting it.  Since the flashlight pluggable transport runs twice in Give mode, it is possible to encounter this condition.  In practice, it was very unlikely, because when you run Lantern for the first time, the get flashlight is extracted immediately, but the give flashlight isn't extracted until you've hit the Give button.  Where I think it was most likely was when you've upgraded Lantern.  At that point, we already know your mode, so when you run we try to start both the get and the give flashlights.  Both will notice that the executable is out of date and try to replace it, encountering this race condition.

The fix is to synchronize on the PT class (e.g. Flashlight).

**Comment by myleshorton** [comment]
Great catch @oxtoacart!

On Tue, Jan 13, 2015 at 7:47 AM, oxtoacart <notifications@github.com> wrote:

> This was a race condition between checking for the existence of the PT
> file and extracting it. Since the flashlight pluggable transport runs twice
> in Give mode, it is possible to encounter this condition. In practice, it
> was very unlikely, because when you run Lantern for the first time, the get
> flashlight is extracted immediately, but the give flashlight isn't
> extracted until you've hit the Give button. Where I think it was most
> likely was when you've upgraded Lantern. At that point, we already know
> your mode, so when you run we try to start both the get and the give
> flashlights. Both will notice that the executable is out of date and try to
> replace it, encountering this race condition.
>
> The fix is to synchronize on the PT class (e.g. Flashlight).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/2168#issuecomment-69764918>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by myleshorton** [comment]
This was closed with https://github.com/getlantern/lantern/pull/2169
