### ISSUE TITLE
Error encrypting stream exception

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#2187]
Seeing this in the Lantern Pi log.

988026 2015-01-23 19:24:56,767 ERROR [Lantern-Jetty-Thread-44] state.ModelIo.write (Storage.java:70) - Error encrypting stream
org.lantern.privacy.UserInputRequiredException: Password has not been provided
	at org.lantern.privacy.DefaultLocalCipherProvider.getLocalKey(DefaultLocalCipherProvider.java:116)
	at org.lantern.privacy.AbstractLocalCipherProvider.newLocalCipher(AbstractLocalCipherProvider.java:145)
	at org.lantern.privacy.DefaultLocalCipherProvider.newLocalCipher(DefaultLocalCipherProvider.java:31)
	at org.lantern.privacy.DefaultEncryptedFileService.localEncryptOutputStream(DefaultEncryptedFileService.java:52)
	at org.lantern.privacy.DefaultEncryptedFileService.localEncryptOutputStream(DefaultEncryptedFileService.java:61)
	at org.lantern.state.Storage.write(Storage.java:61)
	at org.lantern.state.ModelIo.write(ModelIo.java:468)
	at org.lantern.state.ModelIo.write(ModelIo.java:34)
	at org.lantern.state.Storage.write(Storage.java:122)
	at org.lantern.http.InteractionServlet.processRequest(InteractionServlet.java:558)
	at org.lantern.http.InteractionServlet.doPost(InteractionServlet.java:151)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:724)

**Comment by myleshorton** [comment]
Without login on the Pi, storing the model doesn't matter much.

**Comment by atavism** [comment]
@myleshorton Sounds like it would be good to add a quick patch to disable storing the model entirely if skip-login is passed in then?

**Comment by myleshorton** [comment]
I don't think it really affects anything other than noise in the logs though. Is there something you think it's affecting?

**Comment by atavism** [comment]
Nope, just intermittent exceptions appearing in the error log, and I wondered if we wanted to quickly take care of it.

**Comment by myleshorton** [comment]
I would just skip it dude, especially since this will all go away soon with the Go stuff!
