### ISSUE TITLE
panics in server mode

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2364]
Latest valencia branch

`./lantern_darwin_amd64 -role=server`

```
Apr 07 09:54:20.614 - flashlight.server: Server.Configure() called
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4098456]

goroutine 7 [running]:
github.com/getlantern/flashlight/analytics.Configure(0x0, 0xc208050201, 0x0)
	/Users/fffw/workspace/getlantern/flashlight-build/src/github.com/getlantern/flashlight/analytics/analytics.go:39 +0x396
main.runServerProxy(0xc2080c00e0)
	/Users/fffw/workspace/getlantern/flashlight-build/src/github.com/getlantern/flashlight/flashlight.go:278 +0x3fa
main.doMain(0x0, 0x0)
	/Users/fffw/workspace/getlantern/flashlight-build/src/github.com/getlantern/flashlight/flashlight.go:145 +0x563
main._main()
	/Users/fffw/workspace/getlantern/flashlight-build/src/github.com/getlantern/flashlight/flashlight.go:85 +0x1f
github.com/getlantern/systray.func·001()
	/Users/fffw/workspace/getlantern/flashlight-build/src/github.com/getlantern/systray/systray.go:53 +0x55
created by github.com/getlantern/systray.Run
	/Users/fffw/workspace/getlantern/flashlight-build/src/github.com/getlantern/systray/systray.go:54 +0x91

goroutine 1 [syscall, locked to thread]:
github.com/getlantern/systray._Cfunc_nativeLoop(0x0)
	github.com/getlantern/systray/_obj/_cgo_gotypes.go:42 +0x4b
github.com/getlantern/systray.nativeLoop()
	/Users/fffw/workspace/getlantern/flashlight-build/src/github.com/getlantern/systray/systray_nonwindows.go:19 +0x1f
github.com/getlantern/systray.Run(0x45c3da8)
	/Users/fffw/workspace/getlantern/flashlight-build/src/github.com/getlantern/systray/systray.go:56 +0x98
main.main()
	/Users/fffw/workspace/getlantern/flashlight-build/src/github.com/getlantern/flashlight/flashlight.go:77 +0x52
```

**Comment by aranhoide** [comment]
Have you tried supplying the `-addr` argument?  That used to be required,
but maybe that requirement was removed for Valencia.  Maybe it should be
required if `-role=server`, or at least default to `:443`.

**Comment by fffw** [comment]
Oh, it is caused by a nil pointer passed to analytics.

Currently, if any of the arguments is not passed in, it will use the one in lantern.yaml.
