### ISSUE TITLE
[peerscanner] Testing error in Travis

### ISSUE THREAD

**Issue by aranhoide** [getlantern/lantern#2420]
I saw this in https://travis-ci.org/getlantern/flashlight-build/builds/59300036

Via

https://github.com/getlantern/flashlight-build/pull/182#issuecomment-94563529

I couldn't reproduce it locally so maybe it was a temporary glitch with Cloudflare?

```
=== RUN TestEnsureRegistered
cfl: cfl.go:91 cfl-test-entry (127.0.0.1) already registered, looking up existing record
cfl: cfl.go:119 Error updating record &{267787333 getiantem.org cfl-test-entry cfl-test-entry.getiantem.org 127.0.0.1 A  360}, destroying
--- FAIL: TestEnsureRegistered (3.67s)
	Location:	cfl_test.go:47
	Error:		No error is expected but got Error updating record: API Error: 400 Bad Request
	Messages:	Should be able to register with unspecified existing record
		
FAIL
```

**Comment by fffw** [comment]
Encountered another one. https://travis-ci.org/getlantern/lantern/builds/71903172

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x465da0]
goroutine 14 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x181
github.com/getlantern/peerscanner/cfr.TestCreateAndRefresh(0xc2080c6e10)
	/home/travis/gopath/src/github.com/getlantern/lantern/src/github.com/getlantern/peerscanner/cfr/cfr_test.go:48 +0x12b0
```
