### ISSUE TITLE
balancer.Dialer panics "send on closed channel"

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2500]
Encountered while running Lantern with my changes of detour. But this bug may not directly triggered by my changes. Worth take a look.

```
panic: send on closed channel

goroutine 8790 [running]:
github.com/getlantern/balancer.(*dialer).onError(0xc2081abca0, 0x4f3bcc0, 0xc20b7015b0)
	/Users/fffw/workspace/getlantern/lantern/src/github.com/getlantern/balancer/dialer.go:111 +0x6c
github.com/getlantern/balancer.(*Balancer).DialQOS(0xc208a2b980, 0x44f6130, 0x3, 0xc209e4c470, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/fffw/workspace/getlantern/lantern/src/github.com/getlantern/balancer/balancer.go:95 +0x5e0
github.com/getlantern/balancer.(*Balancer).Dial(0xc208a2b980, 0x44f6130, 0x3, 0xc209e4c470, 0xd, 0x0, 0x0, 0x0, 0x0)
	/Users/fffw/workspace/getlantern/lantern/src/github.com/getlantern/balancer/balancer.go:105 +0x89
github.com/getlantern/balancer.*Balancer.Dial·fm(0x44f6130, 0x3, 0xc209e4c470, 0xd, 0x0, 0x0, 0x0, 0x0)
	/Users/fffw/workspace/getlantern/lantern/src/github.com/getlantern/flashlight/client/reverseproxy.go:47 +0x79
github.com/getlantern/detour.func·016()
	/Users/fffw/workspace/getlantern/lantern/src/github.com/getlantern/detour/detour_conn.go:23 +0x5e
created by github.com/getlantern/detour.DialDetour
	/Users/fffw/workspace/getlantern/lantern/src/github.com/getlantern/detour/detour_conn.go:30 +0x16e
```

**Comment by fffw** [comment]
Okay, it's due to a race condition. When a `Balancer` is closed, its dialers will stop together with their `errCh`. In the same or later time,  `Balancer.DialQOS()` calls one of the closed dialer's `onError()`, hence sends on its `errCh`.
