### ISSUE TITLE
Lantern panics

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#2966]
It occurred in a custom build `9915e15 (20150814.013327)` but might also happen in release versions. First panic caught by Lantern but second one caused the program to quit.

```
Aug 18 01:30:07.072 - 1060m2s DEBUG balancer: balancer.go:96 Dialing tcp://mtalk.google.com:5228 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:07.228 - 1060m2s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://cdn9.howtogeek.com:80 on pass 0
Aug 18 01:30:07.233 - 1060m2s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://widgets.outbrain.com:80 on pass 0
Aug 18 01:30:07.288 - 1060m2s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://cdn9.howtogeek.com:80 on pass 0
Aug 18 01:30:07.288 - 1060m2s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://ox-d.tmn.servedbyopenx.com:80 on pass 0
Aug 18 01:30:07.315 - 1060m2s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://cdn9.howtogeek.com:80 on pass 0
Aug 18 01:30:07.315 - 1060m2s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://www.googletagservices.com:80 on pass 0
Aug 18 01:30:07.316 - 1060m2s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://cdn9.howtogeek.com:80 on pass 0
Aug 18 01:30:07.316 - 1060m2s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://cdn9.howtogeek.com:80 on pass 0
Aug 18 01:30:07.331 - 1060m2s ERROR flashlight.client: server.go:1777 http: panic serving 127.0.0.1:63304: runtime error: index out of range
Aug 18 01:30:07.331 - 1060m2s goroutine 307125 [running]:
Aug 18 01:30:07.331 - 1060m2s net/http.func·011()
Aug 18 01:30:07.331 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
Aug 18 01:30:07.331 - 1060m2s bufio.(*Reader).Read(0xc209376420, 0xc20ad78000, 0x2940, 0x8000, 0x2d40, 0x0, 0x0)
Aug 18 01:30:07.331 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:169 +0x251
Aug 18 01:30:07.331 - 1060m2s io.(*LimitedReader).Read(0xc209f2ebe0, 0xc20ad78000, 0x2940, 0x8000, 0x401c52a, 0x0, 0x0)
Aug 18 01:30:07.331 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:408 +0xce
Aug 18 01:30:07.331 - 1060m2s net/http.(*body).readLocked(0xc20a053400, 0xc20ad78000, 0x8000, 0x8000, 0xffffffff, 0x0, 0x0)
Aug 18 01:30:07.331 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transfer.go:584 +0x7a
Aug 18 01:30:07.331 - 1060m2s net/http.(*body).Read(0xc20a053400, 0xc20ad78000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Aug 18 01:30:07.345 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transfer.go:579 +0x115
Aug 18 01:30:07.345 - 1060m2s net/http.(*bodyEOFSignal).Read(0xc20a053440, 0xc20ad78000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Aug 18 01:30:07.345 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:1193 +0x285
Aug 18 01:30:07.345 - 1060m2s io.Copy(0xc83e8a8, 0xc209d9a6f0, 0x6055e08, 0xc20a053440, 0x175b, 0x0, 0x0)
Aug 18 01:30:07.345 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:362 +0x1f6
Aug 18 01:30:07.345 - 1060m2s net/http/httputil.(*ReverseProxy).copyResponse(0xc20932ba40, 0xc83e8a8, 0xc209d9a6f0, 0x6055e08, 0xc20a053440)
Aug 18 01:30:07.345 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/httputil/reverseproxy.go:177 +0x1c6
Aug 18 01:30:07.345 - 1060m2s net/http/httputil.(*ReverseProxy).ServeHTTP(0xc20932ba40, 0x60461b0, 0xc209c79ea0, 0xc2098dd450)
Aug 18 01:30:07.345 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/httputil/reverseproxy.go:160 +0x7b6
Aug 18 01:30:07.347 - 1060m2s github.com/getlantern/flashlight/client.(*Client).ServeHTTP(0xc20803abe0, 0x60461b0, 0xc209c79ea0, 0xc2098dd450)
Aug 18 01:30:07.347 - 1060m2s 	/Users/merlin/workspace/getlantern/lantern/src/github.com/getlantern/flashlight/client/handler.go:31 +0x336
Aug 18 01:30:07.347 - 1060m2s net/http.serverHandler.ServeHTTP(0xc208148360, 0x60461b0, 0xc209c79ea0, 0xc2098dd450)
Aug 18 01:30:07.347 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
Aug 18 01:30:07.347 - 1060m2s net/http.(*conn).serve(0xc209f7ef00)
Aug 18 01:30:07.347 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
Aug 18 01:30:07.347 - 1060m2s created by net/http.(*Server).Serve
Aug 18 01:30:07.347 - 1060m2s 	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
Aug 18 01:30:07.505 - 1060m2s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://cdn.bttrack.com:80 on pass 0
Aug 18 01:30:07.522 - 1060m3s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://mtalk.google.com:5228 on pass 0
Aug 18 01:30:07.574 - 1060m3s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://d3avqv6zaxegeu.cloudfront.net:80 on pass 0
Aug 18 01:30:07.578 - 1060m3s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://cdn.bttrack.com:80 on pass 0
Aug 18 01:30:07.675 - 1060m3s DEBUG detour: detour.go:171 Direct connection to ox-d.tmn.servedbyopenx.com:80 established too late, close it
Aug 18 01:30:08.192 - 1060m3s DEBUG detour: detour.go:171 Direct connection to cdn.bttrack.com:80 established too late, close it
Aug 18 01:30:08.204 - 1060m3s DEBUG detour: detour.go:171 Direct connection to cdn.bttrack.com:80 established too late, close it
Aug 18 01:30:08.571 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://pki.google.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:08.745 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://platform.twitter.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:08.937 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://api.bttrack.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:08.976 - 1060m4s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://pki.google.com:80 on pass 0
Aug 18 01:30:09.058 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://connect.facebook.net:443 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.073 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://www.google-analytics.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.093 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://pki.google.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.190 - 1060m4s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://platform.twitter.com:80 on pass 0
Aug 18 01:30:09.312 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://api.bttrack.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.346 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://b.scorecardresearch.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.355 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://pixel.quantserve.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.377 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://ox-d.tmn.servedbyopenx.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.380 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://ox-d.tmn.servedbyopenx.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.383 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://tags.bkrtx.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.388 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://ip.casalemedia.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.393 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://ads.pubmatic.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.394 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://purch.sync.go.sonobi.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.406 - 1060m4s DEBUG balancer: balancer.go:96 Dialing tcp://dmp.springserve.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.465 - 1060m4s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://connect.facebook.net:443 on pass 0
Aug 18 01:30:09.466 - 1060m4s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://pki.google.com:80 on pass 0
Aug 18 01:30:09.492 - 1060m4s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://api.bttrack.com:80 on pass 0
Aug 18 01:30:09.499 - 1060m4s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://www.google-analytics.com:80 on pass 0
Aug 18 01:30:09.607 - 1060m5s DEBUG balancer: balancer.go:96 Dialing tcp://pki.google.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.672 - 1060m5s DEBUG balancer: balancer.go:96 Dialing tcp://ml314.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.747 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://b.scorecardresearch.com:80 on pass 0
Aug 18 01:30:09.750 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://pixel.quantserve.com:80 on pass 0
Aug 18 01:30:09.819 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://ox-d.tmn.servedbyopenx.com:80 on pass 0
Aug 18 01:30:09.819 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://ip.casalemedia.com:80 on pass 0
Aug 18 01:30:09.821 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://ox-d.tmn.servedbyopenx.com:80 on pass 0
Aug 18 01:30:09.846 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://ads.pubmatic.com:80 on pass 0
Aug 18 01:30:09.850 - 1060m5s DEBUG balancer: balancer.go:96 Dialing tcp://tag.crsspxl.com:80 with (trusted) chained proxy at 107.191.60.103:443
Aug 18 01:30:09.851 - 1060m5s DEBUG detour: detour.go:171 Direct connection to b.scorecardresearch.com:80 established too late, close it
Aug 18 01:30:09.853 - 1060m5s DEBUG detour: detour.go:171 Direct connection to ads.pubmatic.com:80 established too late, close it
Aug 18 01:30:09.881 - 1060m5s DEBUG detour: detour.go:171 Direct connection to pixel.quantserve.com:80 established too late, close it
Aug 18 01:30:09.921 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://tags.bkrtx.com:80 on pass 0
Aug 18 01:30:09.944 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://api.bttrack.com:80 on pass 0
Aug 18 01:30:09.945 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://purch.sync.go.sonobi.com:80 on pass 0
Aug 18 01:30:09.988 - 1060m5s DEBUG balancer: balancer.go:103 Successfully dialed to tcp://pki.google.com:80 on pass 0
panic: runtime error: slice bounds out of range

goroutine 307625 [running]:
bufio.(*Reader).ReadSlice(0xc20a183b60, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:273 +0x266
bufio.(*Reader).ReadLine(0xc20a183b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20939b170, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).readContinuedLineSlice(0xc20939b170, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/textproto/reader.go:123 +0x6f
net/textproto.(*Reader).ReadMIMEHeader(0xc20939b170, 0x8, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/textproto/reader.go:470 +0xf8
net/http.ReadResponse(0xc20a183b60, 0xc2092d5ba0, 0xc20a831f08, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/response.go:151 +0x6a5
net/http.(*persistConn).readLoop(0xc20913f290)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:862 +0x3cf
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 1 [syscall, 1060 minutes, locked to thread]:
github.com/getlantern/systray._Cfunc_nativeLoop(0x0)
	github.com/getlantern/systray/_obj/_cgo_gotypes.go:42 +0x4b
github.com/getlantern/systray.nativeLoop()
	/Users/merlin/workspace/getlantern/lantern/src/github.com/getlantern/systray/systray_nonwindows.go:19 +0x1f
github.com/getlantern/systray.Run(0x4603378)
	/Users/merlin/workspace/getlantern/lantern/src/github.com/getlantern/systray/systray.go:56 +0x98
main.runOnSystrayReady(0x4603378)
	/Users/merlin/workspace/getlantern/lantern/src/github.com/getlantern/flashlight/systray.go:14 +0x28
main.main()
	/Users/merlin/workspace/getlantern/lantern/src/github.com/getlantern/flashlight/flashlight.go:92 +0x52
```

**Comment by myleshorton** [comment]
haven't seen this particular one in awhile.
