### ISSUE TITLE
http: panic serving 127.0.0.1:65240: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3057]
Occured lots of times.
```
Aug 28 06:51:03.945 - 171m4s ERROR flashlight.client: server.go:1777 http: panic serving 127.0.0.1:65240: runtime error: invalid memory address or nil pointer dereference
goroutine 81629 [running]:
net/http.func·011()
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1130 +0xbb
io.Copy(0xc33ad58, 0xc2095d6500, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:362 +0x1f0
net.genericReadFrom(0x4d9e290, 0xc208f63fa8, 0x0, 0x0, 0x4507f70, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:404 +0xb5
net.(*TCPConn).ReadFrom(0xc208f63fa8, 0x0, 0x0, 0x4d9f170, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:72 +0xe5
io.Copy(0x4d9e290, 0xc208f63fa8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:358 +0x13d
github.com/getlantern/flashlight/client.pipeData(0x4d9d690, 0xc208f63fa8, 0x0, 0x0, 0xc20a0f9260)
	/Users/merlin/workspace/getlantern/lantern/src/github.com/getlantern/flashlight/client/handler.go:136 +0x1c7
github.com/getlantern/flashlight/client.(*Client).intercept(0xc20803b040, 0x4d9ec60, 0xc20845bae0, 0xc208787ee0)
	/Users/merlin/workspace/getlantern/lantern/src/github.com/getlantern/flashlight/client/handler.go:105 +0x75d
github.com/getlantern/flashlight/client.(*Client).ServeHTTP(0xc20803b040, 0x4d9ec60, 0xc20845bae0, 0xc208787ee0)
	/Users/merlin/workspace/getlantern/lantern/src/github.com/getlantern/flashlight/client/handler.go:30 +0x1b3
net/http.serverHandler.ServeHTTP(0xc2082e3e60, 0x4d9ec60, 0xc20845bae0, 0xc208787ee0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20845b680)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/server.go:1751 +0x35e
```

**Comment by myleshorton** [comment]
Did you see this locally or in the logs or both @fffw?

**Comment by fffw** [comment]
I saw it locally. But by searching Loggly at this moment, I found the
earliest version is 0d0e46b (20150728.014450).

**Comment by myleshorton** [comment]
Thanks @fffw. I *think* it's because that connection was closed by another go routine but still looking at it.

**Comment by atavism** [comment]
It looks like we're possibly calling ``io.Copy`` on a nil connOut in pipeData. We aren't checking for an error after dialing (lines 97-101) in ``handler.go``

**Comment by myleshorton** [comment]
Ha yes very good point @atavism! I'll add those error checks.

**Comment by myleshorton** [comment]
Interestingly errcheck did not catch this
