### ISSUE TITLE
Nil pointer issue handing http intercept

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3130]
```
ERROR flashlight.client: server.go:1777 http: panic serving 127.0.0.1:49862: runtime error: invalid memory address or nil pointer dereference
goroutine 3162 [running]:
net/http.func??011()
	/go/src/net/http/server.go:1130 +0xa8
github.com/getlantern/detour.(*Conn).Close(0x1269a900, 0x0, 0x0)
	/lantern/src/github.com/getlantern/detour/detour.go:312 +0x2ab
github.com/getlantern/flashlight/client.func??007()
	/lantern/src/github.com/getlantern/flashlight/client/handler.go:65 +0x123
sync.(*Once).Do(0x122d3780, 0x122d3790)
	/go/src/sync/once.go:44 +0xb9
github.com/getlantern/flashlight/client.(*Client).intercept(0x11d4e900, 0x13cd50, 0x129c51f0, 0x129c5ce0)
	/lantern/src/github.com/getlantern/flashlight/client/handler.go:104 +0x5b9
github.com/getlantern/flashlight/client.(*Client).ServeHTTP(0x11d4e900, 0x13cd50, 0x129c51f0, 0x129c5ce0)
	/lantern/src/github.com/getlantern/flashlight/client/handler.go:30 +0x14e
net/http.serverHandler.ServeHTTP(0x11e56780, 0x13cd50, 0x129c51f0, 0x129c5ce0)
	/go/src/net/http/server.go:1703 +0x145
net/http.(*conn).serve(0x11e88d80)
	/go/src/net/http/server.go:1204 +0x9d8
created by net/http.(*Server).Serve
	/go/src/net/http/server.go:1751 +0x2ce
```

**Comment by myleshorton** [comment]
@fffw I'm wondering if we should ignore this for now and just wait for the new detour. What do you think?

**Comment by fffw** [comment]
Agreed @myleshorton . New detour is already in valencia

**Comment by fffw** [comment]
Ok, it's the last statement in the `defer` call in `ServeHTTP` that causes the panic because detour can return non-nil value even when error is encountered. No harm though annoying.
