### ISSUE TITLE
Unable to get implementation class: Didn't find class "org.lantern.mobilesdk.embedded.EmbeddedLantern"

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3632]
Looks like the new dynamic class loading in ``doEnable`` is causing issues with release builds that's preventing Lantern from proxying. After building a new release off valencia, I encountered this fatal error when I switch Lantern on:

```
VpnService  E  Fatal error
 E  org.b.a.b: Unable to get implementation class: Didn't find class "org.lantern.mobilesdk.embedded.EmbeddedLantern" on path: DexPathList[[zip fil e "/data/app/org.getlantern.lantern-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.getlantern.lantern-1, /vendor/lib, /system/lib]] E      at org.b.a.a.bo(Lantern.java:85)
 E      at org.b.a.a.b(Lantern.java:59)
 E      at org.b.a.a.a(Lantern.java:40)
 E      at org.getlantern.lantern.vpn.Service.run(Service.java:47) E      at java.lang.Thread.run(Thread.java:841)
 E  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.lantern.mobilesdk.embedded.EmbeddedLantern" on path: DexPathList[[zip file "/data/app/org.getlantern.lantern-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.getlantern.lantern-1, /vendor/lib, /system/lib]] E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67) E      at java.lang.ClassLoader.loadClass(ClassLoader.java:497) E      at java.lang.ClassLoader.loadClass(ClassLoader.java:457) E      at org.b.a.a.bo(Lantern.java:82)
 E      ... 4 more
 E  Lantern terminated.
```

**Comment by myleshorton** [comment]
This was running the apk @atavism or running `make android-install` or whatever? The latter worked OK for me.

**Comment by atavism** [comment]
It happens while running the APK, when I go to start Lantern and the native library is loaded.

**Comment by atavism** [comment]
cc @oxtoacart

**Comment by oxtoacart** [comment]
I was able to reproduce this on a release build.

**Comment by oxtoacart** [comment]
It's ProGuard, fixing now.
