### ISSUE TITLE
EMADialTime call in balancer causes runtime error on Android

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3802]
I just pulled in the latest changes from devel, and I'm seeing this. Related to recent changes from [here](https://github.com/getlantern/lantern/commit/9854b5c726cbc1fe946bea2f825ffb4aeb3f994c) and [here](https://github.com/getlantern/lantern/blob/9854b5c726cbc1fe946bea2f825ffb4aeb3f994c/src/github.com/getlantern/balancer/dialer.go#L94)

```
                     Go  E  panic: runtime error: invalid memory address or nil pointer dereference
                         E  [signal 0xb code=0x1 addr=0x4 pc=0x78713070]
                         E  goroutine 10 [running]:
                         E  sync/atomic.loadUint64(0x8945840c, 0x0, 0x0)
                         E      /Users/todd/go/src/sync/atomic/64bit_arm.go:10 +0x54
                         E  github.com/getlantern/balancer.(*dialer).EMADialTime(0x894583f0, 0x0, 0x28)
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/balancer/dialer.go:94 +0x40
                         E  github.com/getlantern/balancer.QualityFirst.func1(0x1, 0x0, 0x7866f32c)
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/balancer/strategy.go:41 +0x160
                         E  github.com/getlantern/balancer.(*dialerHeap).Less(0x89458458, 0x1, 0x0, 0x1)
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/balancer/strategy.go:85 +0x34
                         E  container/heap.down(0x783bb280, 0x89458458, 0x0, 0x2)
                         E      /Users/todd/go/src/container/heap/heap.go:111 +0xa8
                         E  container/heap.Init(0x783bb280, 0x89458458)
                         E      /Users/todd/go/src/container/heap/heap.go:45 +0x74
                         E  github.com/getlantern/balancer.New(0x78cc15c8, 0x8a069d60, 0x2, 0x2, 0x0)
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/balancer/balancer.go:45 +0x3f4
                         E  github.com/getlantern/flashlight/client.(*Client).initBalancer(0x893a8060, 0x897ce630, 0x78cc1664, 0x0, 0x0)
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/flashlight/client/balancer.go:43 +0x354
                         E  github.com/getlantern/flashlight/client.(*Client).Configure(0x893a8060, 0x897ce630, 0x78cc1664)
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/flashlight/client/client.go:172 +0x458
                         E  github.com/getlantern/flashlight.applyClientConfig(0x893a8060, 0x892fa190, 0x78cc1664)
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/flashlight/flashlight.go:146 +0x1f4
                         E  github.com/getlantern/flashlight.Run(0x78c0eaf0, 0xb, 0x78c0eaf0, 0xb, 0x892d6810, 0x30, 0x0, 0x78cc1664, 0x892e3780, 0x78cc1668, ...)
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/flashlight/flashlight.go:89 +0x314
                         E  github.com/getlantern/lantern.run(0x892d6810, 0x30)
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/lantern/lantern.go:98 +0x264
                         E  created by github.com/getlantern/lantern.Start.func1
                         E      /Users/todd/Dev/go/src/github.com/getlantern/lantern/src/github.com/getlantern/lantern/lantern.go:60 +0x44
```

**Comment by atavism** [comment]
This is related to alignment of atomic values on ARM. Moving the ``emaDialTime`` field to the top of the dialer struct resolves it.
