### ISSUE TITLE
"ClassNotFoundException: org.msgpack.core.buffer.MessageBufferU" with Android release builds

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#3840]
This problem originates in the pubsub package. I remember we encountered something similar with the Lantern SDK. 

```
                    E  Process: org.getlantern.lantern:PubSubService, PID: 15970
                         E  java.lang.ExceptionInInitializerError
                         E      at org.c.a.a.e.<init>(OutputStreamBufferOutput.java:40)
                         E      at org.c.a.h.c(MessagePack.java:292)
                         E      at org.c.a.f.b(MessagePack.java:152)
                         E      at org.lantern.pubsub.a.e(Client.java:158)
                         E      at org.lantern.pubsub.a.oX(Client.java:135)
                         E      at org.lantern.pubsub.a.run(Client.java:127)
                         E      at java.lang.Thread.run(Thread.java:841)
                         E  Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.msgpack.core.buffer.MessageBufferU
                         E      at org.c.a.a.b.<clinit>(MessageBuffer.java:151)
                         E      ... 7 more
                         E  Caused by: java.lang.ClassNotFoundException: org.msgpack.core.buffer.MessageBufferU
                         E      at java.lang.Class.classForName(Native Method)
                         E      at java.lang.Class.forName(Class.java:251)
                         E      at java.lang.Class.forName(Class.java:216)
                         E      at org.c.a.a.b.<clinit>(MessageBuffer.java:142)
                         E      ... 7 more
                         E  Caused by: java.lang.NoClassDefFoundError: org/msgpack/core/buffer/MessageBufferU
                         E      ... 11 more
                         E  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.msgpack.core.buffer.MessageBufferU" on path: DexPathList[[zip file "/data/app/org.getlant
                            ern.lantern-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.getlantern.lantern-1, /vendor/lib, /system/lib]]
                         E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
                         E      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                         E      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                         E      ... 11 more
```

**Comment by oxtoacart** [comment]
@atavism against which branch/repo can I test my fix?

**Comment by myleshorton** [comment]
Oh right this is totally from proguard -- seems like this will break notifications @atavism but shouldn't affect the current production release right @atavism?
