### ISSUE TITLE
Issue loading feed thumbnails on Android 4.x devices

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4240]
I just tried running Lantern 2.2.0 on my Samung Galaxy S5 (Android 4.4.4) device. Whenever I flip between feeds, none of the images are loading, and I'm seeing the following in the log for every image request:

```
             System.err  W  javax.net.ssl.SSLException: Fatal alert received internal_error
                         W      at com.android.org.conscrypt.SSLEngineImpl.unwrap(SSLEngineImpl.java:484)
                         W      at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
                         W      at com.b.a.o.a(AsyncSSLSocketWrapper.java:191)
                         W      at com.b.a.bt.c(Util.java:23)
                         W      at com.b.a.d.vU(AsyncNetworkSocket.java:146)
                         W      at com.b.a.s.b(AsyncServer.java:788)
                         W      at com.b.a.s.a(AsyncServer.java:626)
                         W      at com.b.a.s.c(AsyncServer.java:41)
                         W      at com.b.a.u.run(AsyncServer.java:568)
```

This looks to be an issue with ``Ion`` documented [here](https://github.com/koush/ion/issues/559) and [here](https://github.com/koush/ion/issues/661). It only happens with release builds when ``minifyEnabled`` is set to true.

**Comment by atavism** [comment]
@myleshorton I confirmed this isn't an issue with [glide](https://github.com/bumptech/glide) which seems better maintained anyway. I opened a PR to switch frameworks [here](https://github.com/getlantern/lantern/pull/4241) -- should I merge to the ``release-2.2.0`` branch still?
