### ISSUE TITLE
[Mobile] Subscriber class org.lantern.activity.PlansActivity and its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern#4770]
This is affecting release builds only:

```
E  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.getlantern.lantern/org.lantern.activity.PlansActivity_}: org.greenrobot.eventbus.h: Subscriber class org.lantern.activity.PlansActivity_ and its super classes have no public methods with the @Subscribe annotation
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523)
E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2582)
E      at android.app.ActivityThread.access$900(ActivityThread.java:174)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E      at android.os.Handler.dispatchMessage(Handler.java:102)
E      at android.os.Looper.loop(Looper.java:146)
E      at android.app.ActivityThread.main(ActivityThread.java:5731)
E      at java.lang.reflect.Method.invokeNative(Native Method)
E      at java.lang.reflect.Method.invoke(Method.java:515)
E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
E      at dalvik.system.NativeStart.main(Native Method)
E  Caused by: org.greenrobot.eventbus.h: Subscriber class org.lantern.activity.PlansActivity_ and its super classes have no public methods with the @Subscribe annotation
E      at org.greenrobot.eventbus.p.a(Unknown Source)
E      at org.greenrobot.eventbus.c.a(Unknown Source)
E      at org.lantern.activity.am.g(Unknown Source)
E      at org.lantern.activity.PlansActivity_.a(Unknown Source)
E      at org.a.a.a.c.a(Unknown Source)
E      at org.lantern.activity.PlansActivity_.setContentView(Unknown Source)
E      at org.lantern.activity.PlansActivity_.onCreate(Unknown Source)
E      at android.app.Activity.performCreate(Activity.java:5580)
E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2487)
E      ... 11 more
```

**Comment by atavism** [comment]
Fixed on the pro-backend branch with a couple proguard updates.
