### ISSUE TITLE
Panics when logging error

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#4803]
Happens occasionally. Binary is built from commit getlantern/lantern-pro@88e4c9694f4bc5924e8b63ac8937aa8eb3013a41, but should be something with lantern itself.

```
ERROR balancer: balancer.go:110 Caused by: dial tcp <masked>:443: connect: network is unreachable

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x428398c]

goroutine 57 [running]:
panic(0x45c2f40, 0xc82000a100)
	/Users/fffw/workspace/go-darwin-amd64-bootstrap/src/runtime/panic.go:481 +0x3e6
github.com/getlantern/errors.(*structured).MultiLinePrinter.func1(0xc827233f10, 0x4631f0a)
	/Users/fffw/workspace/getlantern/lantern-pro/src/github.com/getlantern/errors/errors.go:228 +0x37c
github.com/getlantern/golog.(*logger).print(0xc82011ca80, 0x5754728, 0xc82027a5c0, 0xc827233f10, 0x5, 0x46767c8, 0x5, 0x4631fa0, 0xc82a149f20)
	/Users/fffw/workspace/getlantern/lantern-pro/src/github.com/getlantern/golog/golog.go:197 +0x52c
github.com/getlantern/golog.(*logger).errorSkipFrames(0xc82011ca80, 0x4631fa0, 0xc82a149f20, 0x1, 0x0, 0x0)
	/Users/fffw/workspace/getlantern/lantern-pro/src/github.com/getlantern/golog/golog.go:262 +0x1c8
github.com/getlantern/golog.(*logger).Errorf(0xc82011ca80, 0x4716e20, 0x1f, 0xc827f62790, 0x1, 0x1, 0x0, 0x0)
	/Users/fffw/workspace/getlantern/lantern-pro/src/github.com/getlantern/golog/golog.go:267 +0xbc
github.com/getlantern/flashlight/config.(*fetcher).pollForConfig(0xc8202bc780, 0x65d6640, 0xc8298101b0, 0x47b0530, 0xda0951330, 0x0, 0x0)
	/Users/fffw/workspace/getlantern/lantern-pro/src/github.com/getlantern/flashlight/config/fetcher.go:121 +0x1ff
github.com/getlantern/flashlight/config.Init.func3(0x65d6640, 0xc8298101b0, 0xc8298101b0, 0x0, 0x0, 0x0)
...
```

**Comment by fffw** [comment]
[The line](https://github.com/getlantern/lantern-pro/blob/88e4c9694f4bc5924e8b63ac8937aa8eb3013a41/src/github.com/getlantern/errors/errors.go#L228) triggers the panic is `if err.callStack != nil && len(err.callStack) > 0`, which means `err` is nil.

We probably can refine `(*structured)MultiLinePrinter` a bit to avoid calling it multiple times.

**Comment by fffw** [comment]
To be more specific, look at ```[signal 0xb code=0x1 **addr=0x48** pc=0x428398c]```. `err.callStack` is at offset `0x48`. As in C++, calling a method with `nil` won't panic, only accessing an attribute will do.

**Comment by myleshorton** [comment]
Can't we just reverse the order @fffw and do something like:

```
if err == nil || err.cause == nil {
    return false
}
```

**Comment by fffw** [comment]
Yes we can patch it like that, but it feels to me that the code need to be refactored a bit to avoid such subtle errors.

A wip PR is at https://github.com/getlantern/lantern/pull/4863
