### ISSUE TITLE
lantern crashes at start up on raspberry pi 2

### ISSUE THREAD

**Issue by nebulakl** [getlantern/lantern#5061]
Here is log output

Jul 21 03:25:30.817 - 0m2s DEBUG i18n: translate.go:105 Setting locale en_GB
Jul 21 03:25:30.835 - 0m2s DEBUG flashlight: app.go:75 map[frontedconfig: help:false readableconfig:false test.blockprofilerate:1 test.run: test.memprofilerate:0 test.parallel:4 test.trace: cpuprofile: force-auth-token: test.count:1 test.v:false country:xx registerat: startup:false stickyconfig:false test.benchmem:false test.benchtime:1s test.cpuprofile: uiaddr:127.0.0.1:16823 clear-proxy-settings:false cloudconfig: cloudconfigca: test.memprofile: test.outputdir: test.short:false addr: borda-report-interval:5m0s headless:true memprofile: test.coverprofile: borda-sample-percentage:0.01 configdir: obfs4-distBias:false pprofaddr: staging:false test.bench: test.timeout:0 force-proxy-addr: proxyall:false test.blockprofile: test.cpu:]
Jul 21 03:25:30.836 - 0m2s DEBUG flashlight: flashlight.go:162 ---- flashlight version: d69f472, release: 9999.99.99, build revision date: 20160714.231853 ----
Jul 21 03:25:30.836 - 0m2s DEBUG flashlight: flashlight.go:89 Initializing configuration
Jul 21 03:25:30.838 - 0m2s DEBUG flashlight.config: fetcher.go:76 Not configuring for staging. Using flags: map[cloudconfigca: test.memprofile: test.outputdir: test.short:false clear-proxy-settings:false cloudconfig: headless:true memprofile: test.coverprofile: addr: borda-report-interval:5m0s obfs4-distBias:false pprofaddr: staging:false test.bench: test.timeout:0 borda-sample-percentage:0.01 configdir: test.blockprofile: test.cpu: force-proxy-addr: proxyall:false readableconfig:false test.blockprofilerate:1 test.run: frontedconfig: help:false test.trace: test.memprofilerate:0 test.parallel:4 test.count:1 cpuprofile: force-auth-token: startup:false stickyconfig:false test.benchmem:false test.benchtime:1s test.cpuprofile: test.v:false country:xx registerat: uiaddr:127.0.0.1:16823]
Jul 21 03:25:30.838 - 0m2s DEBUG flashlight.config: fetcher.go:92 Will poll for config at http://config.getiantem.org/cloud.yaml.gz (http://d2wi0vwulmtn99.cloudfront.net/cloud.yaml.gz)
Jul 21 03:25:30.839 - 0m2s DEBUG flashlight.config: config.go:163 Using config dir /home/pi/.lantern
Jul 21 03:25:32.813 - 0m4s DEBUG yamlconf: yamlconf_disk.go:130 **********************\* Read from disk in 1.972668134s
Jul 21 03:25:32.814 - 0m4s DEBUG flashlight.config: config.go:70 Found 2 chained servers in config on disk
Jul 21 03:25:32.815 - 0m4s DEBUG flashlight.config: config.go:72 chained server: &{104.236.117.243:36135 -----BEGIN CERTIFICATE-----
MIID8jCCAtqgAwIBAgIEd0XdcTANBgkqhkiG9w0BAQsFADCBoDELMAkGA1UEBhMCVVMxDjAMBgNV
BAgTBVRleGFzMRswGQYDVQQHExJVbmNvbnRyb2xsZWQgRm9hbXMxEzARBgNVBAoTCkRlcG9ydG1l
bnQxJDAiBgNVBAsTG0ZhbnRhc2llZCBTYWxhbWkgQ29zcG9uc29yczEpMCcGA1UEAxMgUmVjdGls
aW5lYXIgTGF5ZXR0ZSBOYXJ5IERldGVjdHMwHhcNMTYwNDA3MTg1OTI1WhcNMTcwNDA3MTg1OTI1
WjCBoDELMAkGA1UEBhMCVVMxDjAMBgNVBAgTBVRleGFzMRswGQYDVQQHExJVbmNvbnRyb2xsZWQg
Rm9hbXMxEzARBgNVBAoTCkRlcG9ydG1lbnQxJDAiBgNVBAsTG0ZhbnRhc2llZCBTYWxhbWkgQ29z
cG9uc29yczEpMCcGA1UEAxMgUmVjdGlsaW5lYXIgTGF5ZXR0ZSBOYXJ5IERldGVjdHMwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD8PYrsMaczd6DeUui+eFhbiW4MjKKsZfgum/GRwAeZ
C9KUZkUXo0Eb5NMcFDZuEv/vFL/5xHaZ4XZShLyWKSd77z32M016oTnzu2i2IfBitNxrQyrV1RVL
TAMT/mf9C+uGCd9XLXS817OhUSYg6dRRKDNWXV+J5prPP4ZRkzA1Scr6J39YcKMOTPTvAtFdJke4
z0ssfEQEZPpS0EaAmwfEImRrbmu1lJOitatXX/O5IZKaV5yJA3PwQ0BzcC5HxA3SXlKBRLzMqZph
QxvETwNKmB0lW9wPvUjVr8ruh8uEhmkbmKgxzUQZ0hO6AmuPa6hRpZprB1LiFzB33NMmAqlPAgMB
AAGjMjAwMA8GA1UdEQQIMAaHBGjsdfMwHQYDVR0OBBYEFITbZRh43wex0PXw9E5IY5P/vl+5MA0G
CSqGSIb3DQEBCwUAA4IBAQA5TXfolDBhda7xAYRklQ3uuqiKVeDsakSf/kj4t7WSzZlEXd1RlLbX
l0AjPj0Ugz4w97IkLihKlipQG93+6ULneqSJGABK8QFwq3zLHI9CTF2IF3HBt3KflLKZm6pyrnAl
3thEI+3ox385QOLAb53nh5BF2aKm3kgwBdX1D4c9A5tAxQsArQozSIO1VAX4P9LHMc/F/MS734pv
RYFvL5b28ZgKF1GoncsHXiCrLU2YKwHo+5OIVsg1dBcK7fWDAt1MhjQL/WjlrOju+A2poufay918
eq40K9vsiqSV1pErB5W6f6LshLWBqTyWomgKFkJxsNx8JMUl3fGI9oMdrUs7
-----END CERTIFICATE----- CuUjL1GWGyLV8aex9Vq18eI06ECpsc9OmqQmTnUpWlvI4we2KWOyw0d8uPzyFCOt true  map[]}
Jul 21 03:25:32.816 - 0m4s DEBUG flashlight.config: config.go:72 chained server: &{139.59.245.88:59738 -----BEGIN CERTIFICATE-----
MIIDkjCCAnqgAwIBAgIEKmUCvzANBgkqhkiG9w0BAQsFADBxMQswCQYDVQQGEwJVUzETMBEGA1UE
CBMKV2FzaGluZ3RvbjETMBEGA1UEBxMKVGhpcnRlZW50aDEWMBQGA1UEChMNQ2hhZ3JpbnMgTWlr
ZTEgMB4GA1UEAxMXSW5jYXJjZXJhdGluZyBSZWxpZ2lvdXMwHhcNMTYwNTI3MDMwNTU0WhcNMTcw
NTI3MDMwNTU0WjBxMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjETMBEGA1UEBxMK
VGhpcnRlZW50aDEWMBQGA1UEChMNQ2hhZ3JpbnMgTWlrZTEgMB4GA1UEAxMXSW5jYXJjZXJhdGlu
ZyBSZWxpZ2lvdXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCDUTKb+IcJYqaD85tL
fJujoI7dmqWvQqSl0X0vfkngSn8Rf9h8/zwALeujGzM8AVN9PcWn3zOMo+YmmpNJXNTfa5DVrlk1
xRrBk/i6mVSTViYsAgoEYTYPHkwbea76wPHjBi9FKMv7LW9ioBqyAgIIo9/0BzlaIJpWFl6V+7MT
HJQ0NzaE5i262CGWm3vrfB27KE9sJ6sP0H2Qe13LgW6ebOya2291+TGCccFz8sATufKWi9PjAP0f
epZMUDshDpxavGL22v1EU9Zt4OQcQiAvXdUopVxWkSLIoJ6l4YUnJRW1qsLNtsGBVJdz+oXsJ9hB
RyTdfUVs/52L8xse0lEvAgMBAAGjMjAwMA8GA1UdEQQIMAaHBIs79VgwHQYDVR0OBBYEFGY35p3N
euvehsrCvKxMaLQbNJXKMA0GCSqGSIb3DQEBCwUAA4IBAQAo12lORMUpACyU++mWp2T913lkYjf1
R4b9/2m6wAyG/vJ5VA5d8by2ZCkFEBC36lH32hzb7iCXffhlofR6W8oIJ0BwWGKMMykXD1PdOD1E
cNlVpOSeTWIS54HQysH0kuOqf+m6pexZg8XxwAClNE1B3BiKYoMLQ0p2zZN2VpS25vhDuyXAREFI
guU+ePz1714mHq1j6+I8g1icvmHIMkyLnFJw7k4AgO9+lZNTLQUzv/amX1JmbP6mXcuHxEPjw8Aa
mv+49XbQhXvVR2kZWmlz7kkfH8IKW6hCjLp2h8E0w3I+0zfLNJ9L3/++dG6Lzn692nrEn1FqU4Dc
ON1sQ9fQ
-----END CERTIFICATE----- qevvqu1sDdk50TraGmVCp2Tz7BTauGv7uz5MoR4fPn3pg9ZTviFEc12NKV4GVWgZ true  map[]}
Jul 21 03:25:32.817 - 0m4s DEBUG yamlconf: yamlconf_disk.go:68 Configuration changed on disk, applying
Jul 21 03:25:32.817 - 0m4s DEBUG yamlconf: yamlconf.go:165 Loading per session setup
Jul 21 03:25:34.774 - 0m6s DEBUG flashlight.config: config.go:136 Returning config
Jul 21 03:25:34.775 - 0m6s DEBUG flashlight: app.go:109 Got first config
Jul 21 03:25:34.777 - 0m6s DEBUG flashlight.config: bootstrap.go:141 Opening bootstrap file from: /home/pi/.packaged-lantern.yaml
Jul 21 03:25:34.778 - 0m6s DEBUG flashlight.config: bootstrap.go:57 Opening file at: /home/pi/.packaged-lantern.yaml
Jul 21 03:25:34.778 - 0m6s DEBUG flashlight.config: bootstrap.go:61 Error reading file open /home/pi/.packaged-lantern.yaml: no such file or directory
Jul 21 03:25:34.779 - 0m6s DEBUG flashlight.config: bootstrap.go:57 Opening file at: /home/pi/.lantern/.packaged-lantern.yaml
Jul 21 03:25:34.779 - 0m6s DEBUG flashlight.config: bootstrap.go:61 Error reading file open /home/pi/.lantern/.packaged-lantern.yaml: no such file or directory
Jul 21 03:25:34.781 - 0m6s ERROR flashlight: app.go:135 Could not read settings? open /home/pi/.lantern/.packaged-lantern.yaml: no such file or directory [error=Could not read settings? open /home/pi/.lantern/.packaged-lantern.yaml: no such file or directory error_op=open error_type=errors.Error]
ERROR flashlight: app.go:135   at github.com/getlantern/flashlight/app.(_App).beforeStart (app.go:135)
ERROR flashlight: app.go:135   at github.com/getlantern/flashlight/app.(_App).(github.com/getlantern/flashlight/app.beforeStart)-fm (app.go:93)
ERROR flashlight: app.go:135   at github.com/getlantern/flashlight.Run (flashlight.go:98)
ERROR flashlight: app.go:135   at github.com/getlantern/flashlight/app.(*App).Run.func1 (app.go:86)
ERROR flashlight: app.go:135   at runtime.goexit (asm_arm.s:990)
ERROR flashlight: app.go:135 Caused by: open /home/pi/.lantern/.packaged-lantern.yaml: no such file or directory
Jul 21 03:25:34.782 - 0m6s DEBUG flashlight: app.go:141 Starting client UI at 127.0.0.1:16823
Jul 21 03:25:34.783 - 0m6s DEBUG flashlight.ui: ui.go:137 UI available at http://0.0.0.0:16823
Jul 21 03:25:34.784 - 0m6s DEBUG flashlight: bandwidth.go:11 Sending current bandwidth quota to new client
Jul 21 03:25:34.785 - 0m6s DEBUG flashlight: flashlight.go:99 Preparing to start client proxy
Jul 21 03:25:34.785 - 0m6s DEBUG flashlight.geolookup: geolookup.go:57 Requested refresh
Jul 21 03:25:34.787 - 0m6s DEBUG geolookup: geolookup.go:125 Fetching ip... [op=geolookup root_op=geolookup]
Jul 21 03:25:34.788 - 0m6s DEBUG fronted: cache.go:95 Got existing instance
Jul 21 03:25:34.789 - 0m6s DEBUG fronted: direct.go:96 Loading candidates
Jul 21 03:25:34.812 - 0m6s DEBUG flashlight.logging: logging.go:139 Will report to borda
Jul 21 03:25:34.813 - 0m6s DEBUG flashlight.client: client.go:162 Configure() called
Jul 21 03:25:34.813 - 0m6s DEBUG flashlight.client: client.go:171 Client configuration initialized
Jul 21 03:25:34.814 - 0m6s DEBUG flashlight.client: client.go:174 Requiring minimum QOS of 0
Jul 21 03:25:34.815 - 0m6s DEBUG flashlight.proxied: proxied.go:168 Using dual fronter [http_method=GET http_proto=HTTP/1.1 op=chainedandfronted origin=geo.getiantem.org root_op=geolookup]
Jul 21 03:25:34.816 - 0m6s DEBUG borda: borda.go:169 Reporting to Borda every 5m0s
Jul 21 03:25:34.815 - 0m6s DEBUG flashlight.client: balancer.go:22 Adding 2 chained servers
Jul 21 03:25:34.817 - 0m6s DEBUG flashlight.proxied: proxied.go:226 In fronted [http_method=GET http_proto=HTTP/1.1 op=dualfetcher origin=geo.getiantem.org root_op=geolookup]
Jul 21 03:25:34.818 - 0m6s DEBUG flashlight.proxied: proxied.go:246 Sending chained request: false [http_method=GET http_proto=HTTP/1.1 op=dualfetcher origin=geo.getiantem.org root_op=geolookup]
Jul 21 03:25:34.818 - 0m6s DEBUG flashlight.client: balancer.go:29 Adding chained server: 104.236.117.243:36135
Jul 21 03:25:34.818 - 0m6s DEBUG flashlight.proxied: proxied.go:236 Sending request via DDF: false [fronted_url=http://d3u5fqukq7qrhd.cloudfront.net/lookup/ http_method=GET http_proto=HTTP/1.1 op=dualfetcher origin=geo.getiantem.org proxy_type=fronted root_op=geolookup]
Jul 21 03:25:34.822 - 0m6s DEBUG flashlight.client: balancer.go:29 Adding chained server: 139.59.245.88:59738
Jul 21 03:25:34.823 - 0m6s DEBUG flashlight: flashlight.go:129 Starting client HTTP proxy
Jul 21 03:25:34.823 - 0m6s DEBUG flashlight: flashlight.go:121 Starting client SOCKS5 proxy
Jul 21 03:25:34.824 - 0m6s DEBUG flashlight.client: client.go:100 About to listen
Jul 21 03:25:34.824 - 0m6s DEBUG flashlight.client: client.go:152 About to start SOCKS5 client proxy at 127.0.0.1:8788
Jul 21 03:25:34.825 - 0m6s DEBUG flashlight: flashlight.go:131 Started client HTTP proxy
Jul 21 03:25:34.826 - 0m6s DEBUG flashlight.proxiedsites: proxiedsites.go:19 Configuring
Jul 21 03:25:34.826 - 0m6s DEBUG yamlconf: yamlconf.go:231 Polling for new config from yamlconf
Jul 21 03:25:34.827 - 0m6s DEBUG flashlight.config: fetcher.go:111 Polling for config
Jul 21 03:25:34.828 - 0m6s DEBUG flashlight.config: fetcher.go:146 Fetching cloud config from http://config.getiantem.org/cloud.yaml.gz (http://d2wi0vwulmtn99.cloudfront.net/cloud.yaml.gz) [op=fetch_config root_op=fetch_config]
Jul 21 03:25:34.829 - 0m6s DEBUG flashlight.proxied: proxied.go:168 Using dual fronter [http_method=GET http_proto=HTTP/1.1 op=chainedandfronted origin=config.getiantem.org root_op=fetch_config]
Jul 21 03:25:34.831 - 0m6s DEBUG flashlight.proxied: proxied.go:226 In fronted [http_method=GET http_proto=HTTP/1.1 op=dualfetcher origin=config.getiantem.org root_op=fetch_config]
Jul 21 03:25:34.832 - 0m6s DEBUG flashlight.proxied: proxied.go:236 Sending request via DDF: false [fronted_url=http://d2wi0vwulmtn99.cloudfront.net/cloud.yaml.gz?12f8f4fc-0511-4a13-92bb-e33d2d8fdfe5 http_method=GET http_proto=HTTP/1.1 op=dualfetcher origin=config.getiantem.org proxy_type=fronted root_op=fetch_config]
Jul 21 03:25:34.834 - 0m6s DEBUG flashlight.proxied: proxied.go:246 Sending chained request: false [fronted_url=http://d2wi0vwulmtn99.cloudfront.net/cloud.yaml.gz?12f8f4fc-0511-4a13-92bb-e33d2d8fdfe5 http_method=GET http_proto=HTTP/1.1 op=dualfetcher origin=config.getiantem.org proxy_type=fronted root_op=fetch_config]
Jul 21 03:25:34.988 - 0m6s DEBUG proxiedsites: proxiedsites.go:135 Applied updated configuration
Jul 21 03:25:34.989 - 0m6s DEBUG proxiedsites: proxiedsites.go:136 7298 additions, 0 deletions
Jul 21 03:25:34.990 - 0m6s DEBUG flashlight.proxiedsites: proxiedsites.go:31 Updating detour with 7298 additions and 0 deletions
Jul 21 03:25:35.123 - 0m6s DEBUG flashlight: pac.go:152 Setting lantern as system proxy
Jul 21 03:25:35.123 - 0m6s DEBUG flashlight.autoupdate: autoupdate.go:65 Software version: 9999.99.99
Jul 21 03:25:35.123 - 0m6s DEBUG flashlight: pac.go:153 Serving PAC file at http://0.0.0.0:16823/proxy_on.pac
Jul 21 03:25:35.124 - 0m6s DEBUG autoupdate: autoupdate.go:59 Defaulted CheckInterval to 4h0m0s
Jul 21 03:25:35.167 - 0m6s ERROR flashlight: pac.go:205 Unable to set lantern as system proxy: Unable to execute /home/pi/.byteexec/pac-cmd: signal: trace/breakpoint trap

(process:9721): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
 [error=Unable to set lantern as system proxy: Unable to execute /home/pi/.byteexec/pac-cmd: signal: trace/breakpoint trap

(process:9721): GLib-GIO-ERROR *_: No GSettings schemas are installed on the system
 error_op= error_type=errors.Error]
ERROR flashlight: pac.go:205   at github.com/getlantern/flashlight/app.doPACOn (pac.go:205)
ERROR flashlight: pac.go:205   at github.com/getlantern/flashlight/app.pacOn (pac.go:154)
ERROR flashlight: pac.go:205   at github.com/getlantern/flashlight/app.(_App).afterStart (app.go:177)
ERROR flashlight: pac.go:205   at github.com/getlantern/flashlight/app.(_App).(github.com/getlantern/flashlight/app.afterStart)-fm (app.go:94)
ERROR flashlight: pac.go:205   at github.com/getlantern/flashlight.Run.func3 (flashlight.go:138)
ERROR flashlight: pac.go:205   at github.com/getlantern/flashlight/client.(_Client).ListenAndServeHTTP (client.go:114)
ERROR flashlight: pac.go:205   at github.com/getlantern/flashlight.Run (flashlight.go:139)
ERROR flashlight: pac.go:205   at github.com/getlantern/flashlight/app.(*App).Run.func1 (app.go:86)
ERROR flashlight: pac.go:205   at runtime.goexit (asm_arm.s:990)
ERROR flashlight: pac.go:205 Caused by: Unable to execute /home/pi/.byteexec/pac-cmd: signal: trace/breakpoint trap

(process:9721): GLib-GIO-ERROR **: No GSettings schemas are installed on the system

Jul 21 03:25:35.171 - 0m6s DEBUG flashlight: app.go:188 Not opening browser. Startup is: false
Jul 21 03:25:35.172 - 0m6s DEBUG flashlight.client: client.go:123 About to start HTTP client proxy at 127.0.0.1:8787
Jul 21 03:25:35.175 - 0m6s DEBUG flashlight.client: handler.go:44 Reverse proxying GET http://config.getiantem.org/cloud.yaml.gz?12f8f4fc-0511-4a13-92bb-e33d2d8fdfe5 [op=proxy root_op=proxy user_agent=Go-http-client/1.1]
Jul 21 03:25:35.199 - 0m9s DEBUG flashlight.logging: logging.go:142 Will not report to borda
Jul 21 03:25:35.200 - 0m9s ERROR flashlight: app.go:62 panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x23d91c]

goroutine 111 [running]:
panic(0x4c9c18, 0x11126030)
    /usr/local/go/src/runtime/panic.go:481 +0x330
sync/atomic.swapUint64(0x111142bc, 0x1bea6eb0, 0x146330c7, 0x0, 0x0)
    /usr/local/go/src/sync/atomic/64bit_arm.go:41 +0x58
github.com/getlantern/balancer.(_Balancer).Dial(0x11114280, 0x5212e4, 0x3, 0x119d2440, 0x17, 0x0, 0x0, 0x0, 0x0)
    /home/pi/lantern/src/github.com/getlantern/balancer/balancer.go:89 +0xfc
github.com/getlantern/balancer.(_Balancer).Dial-fm(0x5212e4, 0x3, 0x119d2440, 0x17, 0x0, 0x0, 0x0, 0x0)
    /home/pi/lantern/src/github.com/getlantern/flashlight/client/reverseproxy.go:29 +0x5c
github.com/getlantern/detour.Dialer.func1(0x5212e4, 0x3, 0x119d2440, 0x17, 0x0, 0x0, 0x0, 0x0)
    /home/pi/lantern/src/github.com/getlantern/detour/detour.go:146 +0x7ac
github.com/getlantern/flashlight/client.(_Client).proxiedDialer.func1(0x5212e4, 0x3, 0x119d2440, 0x17, 0x0, 0x0, 0x0, 0x0)
    /home/pi/lantern/src/github.com/getlantern/flashlight/client/client.go:218 +0x32c
net/http.(_Transport).dial(0x116a41e0, 0x5212e4, 0x3, 0x119d2440, 0x17, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:708 +0x68
net/http.(_Transport).dialConn(0x116a41e0, 0x0, 0x119d0004, 0x4, 0x119d2440, 0x17, 0xee1698, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:811 +0x1850
net/http.(_Transport).getConn.func4(0x116a41e0, 0x0, 0x119d0004, 0x4, 0x119d2440, 0x17, 0x1120e9c0)
    /usr/local/go/src/net/http/transport.go:755 +0x44
created by net/http.(*Transport).getConn
    /usr/local/go/src/net/http/transport.go:757 +0x1d0

**Comment by fffw** [comment]
It's caused by a bug of go compiler. Moving [`lastDialTime`](https://github.com/getlantern/lantern/blob/devel/src/github.com/getlantern/balancer/balancer.go#L37) to the top of the struct would fix it. Sorry it was fixed but I didn't push it to this repo.
