### ISSUE TITLE
Panic in logging code

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5476]
Noticed this after turning machine off and on, but not sure if that's related:

```
Nov 27 15:46:46.342 - 2401m56s DEBUG flashlight.client: chained.go:215 Error testing dialer 104.155.201.101:48093 to https://ssl.gstatic.com:443/index.html: Unable to dial server fp-obfs4-ggtwnb-20160912-090-obfs4 at 104.155.201.101:48093 [obfs4]: dial tcp 104.155.201.101:48093: connect: network is unreachable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x432e681]

goroutine 52 [running]:
panic(0x46e9ec0, 0xc42000c0e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
github.com/getlantern/flashlight/vendor/github.com/getlantern/errors.(*structured).MultiLinePrinter.func1(0xc4202b57a0, 0x4731c0a)
	/Users/afisk/gopath/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/errors/errors.go:244 +0x3a1
github.com/getlantern/flashlight/vendor/github.com/getlantern/golog.(*logger).print(0xc42001cde0, 0x4b17b60, 0xc4200eabe0, 0x5, 0x4770d5c, 0x5, 0x4731c00, 0xc422d0cb40, 0x0, 0x0)
	/Users/afisk/gopath/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/golog/golog.go:195 +0x27b
github.com/getlantern/flashlight/vendor/github.com/getlantern/golog.(*logger).errorSkipFrames(0xc42001cde0, 0x4731c00, 0xc422d0cb40, 0x1, 0x1, 0x1)
	/Users/afisk/gopath/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/golog/golog.go:261 +0x18c
github.com/getlantern/flashlight/vendor/github.com/getlantern/golog.(*logger).Errorf(0xc42001cde0, 0x477f5ed, 0x19, 0xc42132c320, 0x1, 0x1, 0x4b177a0, 0xc423c1eb40)
	/Users/afisk/gopath/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/golog/golog.go:266 +0xb7
github.com/getlantern/flashlight/config.(*config).poll(0xc4202fe270, 0x4b1b6e0, 0xc42001b630, 0xc420306000, 0x51683c0, 0xdf8475800)
	/Users/afisk/gopath/src/github.com/getlantern/flashlight/config/config.go:197 +0x5d7
created by github.com/getlantern/flashlight/config.pipeConfig
	/Users/afisk/gopath/src/github.com/getlantern/flashlight/config/config.go:129 +0x6a9
```

**Comment by oxtoacart** [comment]
I've not seen this recently.

**Comment by myleshorton** [comment]
OK thanks @oxtoacart closing for now!
