### ISSUE TITLE
Request Android permissions at runtime instead of install time

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#5509]
We should switch to the new Android best practice of requesting permissions at runtime instead of install time, especially if we have a compelling reason to move our target API past 22, since doing so is required if we take that step.

**Comment by myleshorton** [comment]
```                         I  uid=10216(org.getlantern.lantern) expire 4 lines
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: org.getlantern.lantern, PID: 18218
                         E  android.os.FileUriExposedException: file:///sdcard/Lantern.apk exposed beyond app through Intent.getData()
                         E      at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                         E      at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                         E      at android.content.Intent.prepareToLeaveProcess(Intent.java:8933)
                         E      at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
                         E      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
                         E      at android.app.ContextImpl.startActivity(ContextImpl.java:819)
                         E      at android.app.ContextImpl.startActivity(ContextImpl.java:796)
                         E      at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
                         E      at org.lantern.activity.s$a.a(Unknown Source)
                         E      at org.lantern.activity.s$a.onPostExecute(Unknown Source)
                         E      at android.os.AsyncTask.finish(AsyncTask.java:660)
                         E      at android.os.AsyncTask.-wrap1(AsyncTask.java)
                         E      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:154)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6077)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by myleshorton** [comment]
The above is the initial error encountered on a Nexus 6 running android 7 when attempting to use this technique for file system permissions for auto-update. Potential fix is here:

http://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by myleshorton** [comment]
The above is implemented on a branch now -- what is that branch again @atavism?

**Comment by atavism** [comment]
Yes, @myleshorton.. Thanks!
