### ISSUE TITLE
macos sierra 4.1.2版本安装之后启动不了，求解决

### ISSUE THREAD

**Issue by colla2me** [getlantern/lantern#6030]

**Comment by water137780117** [comment]
一样，刚刚突然不能用了，闪退。卸载、重启再安装能用个一两分钟，就又开始闪退

**Comment by zzz4457** [comment]
早上还在用的，突然就自己退出了，吓的我以为是系统被黑了......卸载再安装后，能开启一会儿，过一会儿就会提示蓝灯已停止之类的错误信息，要求重新开启，就再也开不起来了。

**Comment by dawnft** [comment]
Oct 10 08:08:38.030 - 0m0s DEBUG chained: proxy.go:204 Defaulted lampshade pinginterval to 15s
panic: interface conversion: interface {} is *ecdsa.PublicKey, not *rsa.PublicKey

goroutine 59 [running]:
panic(0xa97aa0, 0xc42206eb80)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/getlantern/flashlight/chained.newLampshadeProxy(0xc4210376c0, 0x20, 0xc421080f50, 0xc4203e7390, 0x8, 0xc4203e8d60, 0x0, 0x22, 0xc426161cc8)
	/lantern/src/github.com/getlantern/flashlight/chained/proxy.go:214 +0x883
github.com/getlantern/flashlight/chained.CreateDialer(0xc4210376c0, 0x20, 0xc421080f50, 0xc4203e7390, 0x8, 0xc4203e8d60, 0xc42587b3a8, 0x1, 0xc4210330b0, 0xc42587b380)
	/lantern/src/github.com/getlantern/flashlight/chained/proxy.go:67 +0x58e
github.com/getlantern/flashlight/client.ChainedDialer(0xc4210376c0, 0x20, 0xc425f7def0, 0xc4203e7390, 0x8, 0xc4203e8d60, 0xf6d900, 0xc422214690, 0x0, 0x0)
	/lantern/src/github.com/getlantern/flashlight/client/chained.go:19 +0xdf
github.com/getlantern/flashlight/client.(*Client).initBalancer(0xc420180630, 0xc4210330b0, 0xc4203e7390, 0x8, 0xc4211901f0, 0xc4211900b0)
	/lantern/src/github.com/getlantern/flashlight/client/balancer.go:28 +0x250
github.com/getlantern/flashlight/client.(*Client).Configure(0xc420180630, 0xc4210330b0, 0xc4203e7390, 0x8)
	/lantern/src/github.com/getlantern/flashlight/client/client.go:310 +0xc5
github.com/getlantern/flashlight.Run.func2(0xa8c680, 0xc4210330b0)
	/lantern/src/github.com/getlantern/flashlight/flashlight.go:96 +0xfc
github.com/getlantern/flashlight/config.pipeConfig.func1(0xc424f0e2a0, 0xc42101d200)
	/lantern/src/github.com/getlantern/flashlight/config/config.go:108 +0x74
created by github.com/getlantern/flashlight/config.pipeConfig
	/lantern/src/github.com/getlantern/flashlight/config/config.go:110 +0x82

**Comment by psjmpd** [comment]
应该是因为GFW发力导致的，我这里也是一样

**Comment by yugj** [comment]
今天老版本连不上了，就更新了最新版本，还是不行，买了两年才用了几个月，，，祈祷快点恢复
